---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.ENGINE_NAME}}-certs
data:
  kubernetes.pem: |
    -----BEGIN CERTIFICATE-----
    MIIC2DCCAcCgAwIBAgIRALAvMrTesBHMRIbGFYkrlhswDQYJKoZIhvcNAQELBQAw
    FTETMBEGA1UEAxMKa3ViZXJuZXRlczAeFw0xNzA4MjgxOTU4NTRaFw0yNzA4Mjgx
    OTU4NTRaMBUxEzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUA
    A4IBDwAwggEKAoIBAQDP6nYTjfndvOi18ImbnbvOZ9rwsXqJFELMHU91OeHiqHOi
    OYnTVwrjBh2idLT3J3nEhbs4XTHqYpqQ3vg0W9nUTO2y9fafvTYU944fWQ9uIrNg
    5cD4Ixs+NoY2fvI+q+XQC6HSbDbtKGNS/Jng9HWlk1vw64NPpmNH12mPUo4jFfw9
    fh/tpcY9jElfxIrBATBs4xXp2G8Qk+VBIa9nqxnkULroOKvcOvOx8D55MwWpEJst
    tCYIqG3NqvXLqGSC7nxz1bbMJfcD7AFgofs5mvtniQLpgdowZlMsx6rrU3jARL78
    oNKWGzwspJ68rmwaHfx6TAZWGmLRScOwLembwp4HAgMBAAGjIzAhMA4GA1UdDwEB
    /wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCodkfC
    KcNc69qtzfYVQAej1UoHa28TS9j0uwEWjZU4tUVGg/d3B+f/rv27kjDc7SbIHZ+U
    q2ZLVUgaO99Z2R42PXMU6BEETv5/OKxjgd6QMBqEVLAuMWdZlnpd0JC01FwKIopF
    uiUAhZtcGKIEx5SSuIIJtU8kjgGlnKEzirkQUB9BT9DRCUazT5eJzTUKIYbZ0M/x
    IFLmD/ffYxXfDiR3nXZGYIjdPbGan6eNidLcBGDfLZo6EvBSGaTHyy+12sw6rXSW
    AMQVwpTcfiJS54oqIxCSwrjnW4VXFxbH/zIfW0k93onpDMuxcOm+7Cnf5bFRDvZs
    4BhEujy5xEmj05Ml
    -----END CERTIFICATE-----
  acp_intermediate.pem: |
    -----BEGIN CERTIFICATE-----
    MIIFzDCCA7SgAwIBAgIUMSe1QX1ug5WvIsPsjrXVunIzucEwDQYJKoZIhvcNAQEN
    BQAwazELMAkGA1UEBhMCVUsxDzANBgNVBAgTBkxvbmRvbjEPMA0GA1UEBxMGTG9u
    ZG9uMRMwEQYDVQQKEwpIb21lb2ZmaWNlMQwwCgYDVQQLEwNBQ1AxFzAVBgNVBAMT
    DkhvbWVPZmZpY2UgQUNQMB4XDTE3MDkxMTEyMzgwMFoXDTQ3MDkwNDEyMzgwMFow
    cDELMAkGA1UEBhMCVUsxDzANBgNVBAgTBkxvbmRvbjEPMA0GA1UEBxMGTG9uZG9u
    MRMwEQYDVQQKEwpIb21lb2ZmaWNlMQwwCgYDVQQLEwNBQ1AxHDAaBgNVBAMTE0FD
    UCBJbnRlcm1lZGlhdGUgQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoIC
    AQCik1b7ga+s6DVpjWYkQoo9IvnEPrWER4V2H7GcdspPJTjHBk5ck/i+e8764XQM
    Aaif3oqih2C/MEm4bZGrhk1YvHLUHGDLEZ6gFdJGkGOubXwMBhZU8NEaG2RmDkR3
    VqA6ye324n3n6aARC01gUlQNQomTOOs3Sm9aUTDNOinaoEsjAdgprtuSnIs9uNIG
    KkhPoS2Tim2QHNrn8nbbku/2loUkC0LG8i20IqWhjINg7eNgQLy+h7buP3XxoT3W
    Is54GOv0j48smgUe01Is8LbsqoSIb+MKSNpFmtSMO4kESY1NXaWFw9duje0AubDj
    K+PubCoDEKlCreOXO5P4j0yL5q44AKCUEFUbDjN4ulghAfR9WinFvmYn4JE2V/FZ
    brA5tolZMzJUvy3KqrX+pO3771oMYDCMSwLoAYFBZJt9T2iQR51R6itkvfd3qn/q
    7jl8ig/CrphKYvXKMlFlo5rh8S8Zi2ZBbcpGw4wGNjBCBTsFqFVb9D41XgOeMPZh
    OdtRtejpGyo4KyBNfnVwB9Wjb54y7VPvSDDOk0AZtwR2s3SUAh5S7pg59hd3PSRn
    N0YGKTFNisIxqE6AiPd+rr4Jg9v2m4wDj8CXrTEblnVYCHxoFTuVxTN9Y3j1grw/
    QHjzdzUfPs+Sq041jAAfOUVSRH1dbWXilZkL07w8OEd0+QIDAQABo2MwYTAOBgNV
    HQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU4QAH3mDRQdSK
    DRaDZ7SISCXItI4wHwYDVR0jBBgwFoAULDmx0ITbg+KftWIF9xL6fqP2MBowDQYJ
    KoZIhvcNAQENBQADggIBAMsfp+s4qW4A8Ml29RHGnUjjotZnPiwMN98egsshLrL4
    CcqSeYKT36yreU1h3f68C385XFI5OiSH+8XDBGIxvX2rB8WFBuKrP1itQsRT0t2N
    vAPRyVToA/gZc1K6PlHOEbOD2319OGa9QKOTrNSF1fwzdifAHyb7R9eMvgvdWlbq
    egq+eIoAj25mfvl6MhDhx6FY83hRQ3w9goSMQ9XQuCm+ms/CI7ZHfYeCjRvnpixN
    6n5VTpdDSg7LSl7FOXP0CzW/MN7xMG7BLC5weuyneKP0fJ4oXmBrYzi6gYIWuTIm
    dVdpWAMSVetkp1HsGixlOBTrk+ccRTU8vbCdYvKas1v+0YbwHGG4m1qvO9JnZrcO
    ADqaz3D7gVFm4QMZM+bcSICPqMQlG4cM2jvSOtluM4UAzIbQN3PU88COuYkd/cIk
    xXFOU5yG5BSwaKWhT49pgRKFOt9MQukvyI/l++G8Jtj4yF9gvLoK0Xk8Oe5EsJpQ
    X1T/xYgGN2IRWqKBTwYtzwOOfUse1Gp3HWA9rTpfgmP0VXdMB7rHUf3VMyJTpvZW
    mvZHwxVQc0Cqv80kBDz9jdIkIwzxv6rIHDrH+VUkag8SL/OKR9RmTv384HLfodJd
    rNG369QnCc0A+C5EuuyHCfZ0rchCGfOLaUfgjTZCvMAtNTMmlJBTixMqKKDZnfg9
    -----END CERTIFICATE-----
  acp.pem: |
    -----BEGIN CERTIFICATE-----
    MIIFpjCCA46gAwIBAgIUXnfSwTtlt/NUVIk72Q37HbgV/OgwDQYJKoZIhvcNAQEN
    BQAwazELMAkGA1UEBhMCVUsxDzANBgNVBAgTBkxvbmRvbjEPMA0GA1UEBxMGTG9u
    ZG9uMRMwEQYDVQQKEwpIb21lb2ZmaWNlMQwwCgYDVQQLEwNBQ1AxFzAVBgNVBAMT
    DkhvbWVPZmZpY2UgQUNQMB4XDTE3MDkxMTEyMzUwMFoXDTQ3MDkwNDEyMzUwMFow
    azELMAkGA1UEBhMCVUsxDzANBgNVBAgTBkxvbmRvbjEPMA0GA1UEBxMGTG9uZG9u
    MRMwEQYDVQQKEwpIb21lb2ZmaWNlMQwwCgYDVQQLEwNBQ1AxFzAVBgNVBAMTDkhv
    bWVPZmZpY2UgQUNQMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA1E9s
    cuKdxuo9NVDxvC6mgcjXO4wzmHoGt9ipH4HGE0HrHtOjI79Xxnqt7ILqvmLNR8Am
    lPT6u2WE+HunMgMOGnkph+ZUue/qFzVm6Hw1WnA5aCpi5xdOD7Lj8OT22KxghTPD
    ztEZSNdQbRml3mPPgv3HPiWh0CMFiAKsKPwNGKK4IyYV1wuCyLpGFXJqZzUadtyF
    DEyrANqRa4UcsaTtlsLSJM9JfX3i0q8C/0/+Rj82aVdhe9NdZyeb7l+DS9Q//c55
    1LAvb+kDgiZTrhr3wb3CQhf0J6nqL9MWTSdsYoIjnq97icwz+6Jcx7SXwhUs/lOZ
    ukWRoWUCfFsqXDQg9R9OKNXejxi9i35GgOzcBdDQKNGz85Xua7uTzeQV7ooykzEF
    h6qIKYe1KdsRMV3/3qHt1IhMeMCKTW//RkkX8RnxhgQzb5MeA4LW0RKh/AYvPqjn
    CeWQhuQNaEMh5e5T+mnrjguaB1nlc3L4+1Y8xxBN6J/EGcSjsYJdotaBHhjSDScB
    bGHdJ2vuNVBtNaOu/MmsMXCIstYpdcOKucawLIov2y6hyxpn7Uo49mc6HkpObFZE
    AovPbLe+YKpsXRYiDscC0qtYlp+hlT7W7ZGb7ANe9d/n+pzkvh9Sdnp6vPQVmWYe
    YkPz7mj9cTp/2XtlKgnlJvfjfPxeeZo4H6hsmxkCAwEAAaNCMEAwDgYDVR0PAQH/
    BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFCw5sdCE24Pin7ViBfcS
    +n6j9jAaMA0GCSqGSIb3DQEBDQUAA4ICAQCd1UvjgCnU7Q4VvJx8rcx9VJaDPBem
    /Z2xNaY1lmgugdjMKYrrn35rq+72Z7W5o0AEEYPnDE8qda3esyViIE9iRWGX263W
    CCIgqFNlmRiKYqYjp9m5/8LphZ2dCdAq30ZnyBsFpeI0xe26wYJtOj1UO2O2ipfm
    4FrMOaJg2rlXoEaXg3wwQoRKBrqrfu9vknhF/VBC6CmV2Iq0LffKbS7FFGUNCGTO
    ZeoxCE5Fodu8VXG1UKJjgLmvy4rCa+mISlOzl6SNuUiCH0tvbic5jlyMAsiIy1EJ
    tG0socpRcH3Fl+/mopnjh8Me4avQRO7Q00fnfuRGNCbH9Y7ArpaGNqJZWhthFkjL
    VArtdgtwYyyP7A+LYD4dVvVTY2BFTLk6eLNVLnWKkmzFogF1V3n5GXiUc1PmBQ6L
    UwAAJqteeF9gg4cFZ6W+/2p6iIFgjJYKsI68JPMrmUEkap2+HI15jCjQ+A+iVa+g
    8vVN+Q1mHrAGC5G3F70tDBXDyDPx6A5Fxb8eP8a7Ahg6TMP1VoRQ4XlkLgNFYD3W
    ov6Bq1woB345v+ds2chKMtJzNhzcKjwd8Kt9XKwsGxROfnWhr9oQjElvVTRTvOKU
    jwmL3+zExH+e/cdFzJD4Ex0PvHabqOZoHO3AyYOEIS0P3CbvDJLhDhpgPFRqKe5Y
    fg+3eermn16ARQ==
    -----END CERTIFICATE-----
  acp_prod.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC0zCCAbugAwIBAgIMFQX9Tp+lpXdtuvB/MA0GCSqGSIb3DQEBCwUAMBUxEzAR
    BgNVBAMTCmt1YmVybmV0ZXMwHhcNMTcxMjMxMTIxNjAzWhcNMjcxMjMxMTIxNjAz
    WjAVMRMwEQYDVQQDEwprdWJlcm5ldGVzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
    MIIBCgKCAQEAtmWnkUCi4mg8oqSfSh/GNh5wX1/vOIIxHiH7R8IumftRRcfOQwac
    OOo0VISvRa+palULvjWQBr8IBdXIUQyFQMZXtRfLHAKU+nCV8lEguCo6aPIH30KA
    S+UW9sqvjSKxzWZ52Su8WTudUl+v240WgXpN2oaVfgzdD/qro3vuavXvttkOz7YL
    mE2KLPei5plEqNfStbhmSFyppG/0JR9t9rGUQP240HL54SxbirBpsSsk3JD3MptU
    FNt/ujsF2khfJuFv4N7K5dtfSUSHrNoIcPnfedooRrVKTu2TeroohFx2bYJTWFv/
    1cFYFOPdY4yTEiEff5ZSPGA9YmuHFvex1QIDAQABoyMwITAOBgNVHQ8BAf8EBAMC
    AQYwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAkpA/ebOEcEq8
    CEu3TrGb0VP4oqaOecFVUmTA8a/WPACeZE0+0r2yIFx+rQyfshIDEF+G14n5J7I8
    TVneTqIKNXceYTWmuO2QwBH64zU/KOn8jvS5IFkCTe4kIWl9LgnOCXNocJVTBSsQ
    CXxvhc76qUHzx6WhlrWcn3QYz1nArqxdktCAJrvR0AZyhFztPKpTO6TMrhB6vMZr
    SvEMEb9RDdrcvJC7SNfi/nntpX1rlaWmmjrki24WuvEziqxz4YkdjUf4a6q3TLLw
    4hMP0qOtUN48eNCnvhgXe2A4+nSO4sgAdeiwofEglExASS5WuZhBvMMzZQT+hZcf
    Q1YYDewcPQ==
    -----END CERTIFICATE-----
  acp_notprod.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC2DCCAcCgAwIBAgIRALAvMrTesBHMRIbGFYkrlhswDQYJKoZIhvcNAQELBQAw
    FTETMBEGA1UEAxMKa3ViZXJuZXRlczAeFw0xNzA4MjgxOTU4NTRaFw0yNzA4Mjgx
    OTU4NTRaMBUxEzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUA
    A4IBDwAwggEKAoIBAQDP6nYTjfndvOi18ImbnbvOZ9rwsXqJFELMHU91OeHiqHOi
    OYnTVwrjBh2idLT3J3nEhbs4XTHqYpqQ3vg0W9nUTO2y9fafvTYU944fWQ9uIrNg
    5cD4Ixs+NoY2fvI+q+XQC6HSbDbtKGNS/Jng9HWlk1vw64NPpmNH12mPUo4jFfw9
    fh/tpcY9jElfxIrBATBs4xXp2G8Qk+VBIa9nqxnkULroOKvcOvOx8D55MwWpEJst
    tCYIqG3NqvXLqGSC7nxz1bbMJfcD7AFgofs5mvtniQLpgdowZlMsx6rrU3jARL78
    oNKWGzwspJ68rmwaHfx6TAZWGmLRScOwLembwp4HAgMBAAGjIzAhMA4GA1UdDwEB
    /wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCodkfC
    KcNc69qtzfYVQAej1UoHa28TS9j0uwEWjZU4tUVGg/d3B+f/rv27kjDc7SbIHZ+U
    q2ZLVUgaO99Z2R42PXMU6BEETv5/OKxjgd6QMBqEVLAuMWdZlnpd0JC01FwKIopF
    uiUAhZtcGKIEx5SSuIIJtU8kjgGlnKEzirkQUB9BT9DRCUazT5eJzTUKIYbZ0M/x
    IFLmD/ffYxXfDiR3nXZGYIjdPbGan6eNidLcBGDfLZo6EvBSGaTHyy+12sw6rXSW
    AMQVwpTcfiJS54oqIxCSwrjnW4VXFxbH/zIfW0k93onpDMuxcOm+7Cnf5bFRDvZs
    4BhEujy5xEmj05Ml
    -----END CERTIFICATE-----
